import { ArrowRight, Building2, CalendarClock, CircleDollarSign, Package, TrendingUp } from "lucide-react";
import { PageContainer } from "@/components/layout";
import { Button, Card, CardContent, CardHeader, ChartFrame, MetricCard, StatusIndicator } from "@/components/ui";

export const metadata = { title: "Student dashboard" };

export default function StudentDashboard() {
  return <PageContainer>
    <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><StatusIndicator tone="success">Round 1 active</StatusIndicator><h1 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-4xl">Good morning</h1><p className="mt-1 text-muted">Your simulation overview and next deadline.</p></div><Button size="lg">Make decisions <ArrowRight size={18} /></Button></div>
    <Card className="mb-5 overflow-hidden border-brand-100 bg-linear-to-r from-brand-50 to-white"><CardContent className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-brand-700">Current simulation</p><h2 className="mt-1 text-xl font-bold">N10 Million Challenge</h2><p className="mt-1 text-sm text-muted">Consumer Goods · Round 1 of 6</p></div><div className="flex items-center gap-3 rounded-lg border border-brand-100 bg-white px-4 py-3"><CalendarClock className="text-brand-600" /><div><p className="text-xs text-muted">Decision deadline</p><p className="font-semibold">Not scheduled</p></div></div></CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Starting capital" value="—" detail="Awaiting simulation data" icon={CircleDollarSign} /><MetricCard label="Revenue" value="—" icon={TrendingUp} tone="blue" /><MetricCard label="Inventory" value="—" icon={Package} tone="amber" /><MetricCard label="Company value" value="—" icon={Building2} tone="violet" /></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]"><ChartFrame title="Performance overview" description="Results will appear after a round is processed."><div className="flex min-h-52 items-center justify-center rounded-lg border border-dashed border-border bg-slate-50 text-sm text-muted">No performance data yet</div></ChartFrame><Card><CardHeader><h2 className="font-bold">Next steps</h2></CardHeader><CardContent><ol className="space-y-4 text-sm"><li className="flex gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-brand-100 font-bold text-brand-700">1</span><div><p className="font-semibold">Review the market</p><p className="text-muted">Understand the conditions for this round.</p></div></li><li className="flex gap-3"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-slate-100 font-bold">2</span><div><p className="font-semibold">Make your decisions</p><p className="text-muted">Submit when your team is ready.</p></div></li></ol></CardContent></Card></div>
  </PageContainer>;
}
